import { useCallback, useEffect, useRef } from 'react';
import './ScrollExpand.css';
const clamp=(v,a,b)=>v<a?a:v>b?b:v;
const smooth=(a,b,x)=>{const t=clamp((x-a)/(b-a||1e-6),0,1);return t*t*(3-2*t)};
export default function ScrollExpand({src='',alt='',title='',scrollHint='',startWidth=42,startHeight=58,startRadius=24,endRadius=0,mediaZoom=1.35,scrollDistance=1.2,holdDistance=.35,smoothing=.1,overlayScrim=.45,useWindowScroll=false,enabled=true,children,className='',style}){
 const root=useRef(),track=useRef(),stage=useRef(),frame=useRef(),media=useRef(),heading=useRef(),overlay=useRef(),scrim=useRef(),hint=useRef();
 const props=useRef();props.current={startWidth,startHeight,startRadius,endRadius,mediaZoom,scrollDistance,holdDistance,smoothing,overlayScrim,useWindowScroll,enabled};
 const apply=useCallback(p=>{if(!frame.current||!media.current)return;const c=props.current,e=smooth(0,1,p),w=c.startWidth+(100-c.startWidth)*e,h=c.startHeight+(100-c.startHeight)*e;frame.current.style.clipPath=`inset(${(100-h)/2}% ${(100-w)/2}% ${(100-h)/2}% ${(100-w)/2}% round ${c.startRadius+(c.endRadius-c.startRadius)*e}px)`;media.current.style.transform=`scale(${c.mediaZoom+(1-c.mediaZoom)*e})`;scrim.current.style.opacity=c.overlayScrim*e;if(heading.current){const o=smooth(.4,.88,p);heading.current.style.opacity=1-o;heading.current.style.transform=`translateY(${-28*o}px) scale(${1+.06*o})`}if(hint.current){const g=smooth(0,.12,p);hint.current.style.opacity=1-g}if(overlay.current){const i=smooth(.68,1,p);overlay.current.style.opacity=i;overlay.current.style.transform=`translateY(${18*(1-i)}px)`}},[]);
 useEffect(()=>{let raf=0,current=0,target=0,h=0,running=false;const measure=()=>{h=useWindowScroll?innerHeight:root.current.clientHeight;stage.current.style.height=`${h}px`;track.current.style.height=`${h*(1+scrollDistance+holdDistance)}px`;apply(target)};const read=()=>clamp(useWindowScroll?-track.current.getBoundingClientRect().top/(h*scrollDistance):root.current.scrollTop/(h*scrollDistance),0,1);const tick=()=>{const k=smoothing<=0?1:1-Math.exp(-1/(60*smoothing));current+=(target-current)*k;apply(current);if(Math.abs(target-current)>.0004)raf=requestAnimationFrame(tick);else running=false};const onScroll=()=>{target=enabled?read():1;if(!running){running=true;raf=requestAnimationFrame(tick)}};measure();onScroll();const scroller=useWindowScroll?window:root.current;scroller.addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',measure);return()=>{cancelAnimationFrame(raf);scroller.removeEventListener('scroll',onScroll);removeEventListener('resize',measure)}},[apply,useWindowScroll,scrollDistance,holdDistance,smoothing,enabled]);
 return <div ref={root} className={`scroll-expand ${useWindowScroll?'':'scroll-expand--scroller'} ${className}`} style={style}><div ref={track} className="scroll-expand__track"><div ref={stage} className="scroll-expand__stage"><div ref={frame} className="scroll-expand__frame"><img ref={media} className="scroll-expand__media" src={src} alt={alt}/><div ref={scrim} className="scroll-expand__scrim"/><div ref={overlay} className="scroll-expand__overlay">{children}</div></div>{title&&<div ref={heading} className="scroll-expand__title">{title}</div>}{scrollHint&&<div ref={hint} className="scroll-expand__hint">{scrollHint}</div>}</div></div></div>
}
